### ISSUE TITLE
install failed on Mac ~-~

### ISSUE THREAD

**Issue by RayJune** [sindresorhus/trash#57]
like this
➜  ~ npm install --save trash
npm WARN saveError ENOENT: no such file or directory, open '/Users/rayjune/package.json'
/Users/rayjune
└── trash@4.0.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/rayjune/package.json'
npm WARN rayjune No description
npm WARN rayjune No repository field.
npm WARN rayjune No README data
npm WARN rayjune No license field.

**Comment by SamVerschueren** [comment]
You are trying one of the following things

1. You want to install it globally so that you can run `trash` in your command line
2. You want to install it inside a project so that you can use the `trash` API

In case of `1`, you should install [trash-cli](https://github.com/sindresorhus/trash-cli).

In case of `2`, you ran the `npm` command inside your home directory which doesn't have a `package.json`.

**Comment by RayJune** [comment]
aha ~！ Thank you very very much.
